[completion]
provider = "litellm"
concurrent_request_limit = 1

  [completion.generation_config]
  model = "ollama/llama3.1"
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 1_024
  stream = false
  add_generation_kwargs = { }

[database]
provider = "postgres"  # currently only `postgres` is supported

# Optional parameters (typically set in the environment instead):
user     = "user"
password = "password"
host     = "localhost"
port     = 5432           # Use a numeric port (not quoted)
db_name  = "vector_store"
# not specified here, but note: `app.project_name` sets the root path (schema/prefix) to all R2R tables.

[embedding]
provider = "ollama"
base_model = "mxbai-embed-large"
base_dimension = 1_024
batch_size = 32
add_title_as_prefix = true
concurrent_request_limit = 32

[ingestion]
excluded_parsers = [ "mp4" ]
