services:
  vector_store:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=vector_store
    ports:
      - "5432:5432"
